"""quat: quaternion rotation kernels built on the standard library."""

from .core import (
    EPS,
    QuatError,
    angle_between,
    as_quaternion,
    as_vector,
    compose,
    conjugate,
    dot,
    from_axis_angle,
    from_euler,
    identity,
    inverse,
    multiply,
    norm,
    normalize,
    rotate,
    slerp,
    to_axis_angle,
    to_euler,
)

__all__ = [
    "EPS",
    "QuatError",
    "angle_between",
    "as_quaternion",
    "as_vector",
    "compose",
    "conjugate",
    "dot",
    "from_axis_angle",
    "from_euler",
    "identity",
    "inverse",
    "multiply",
    "norm",
    "normalize",
    "rotate",
    "slerp",
    "to_axis_angle",
    "to_euler",
]
